from .Icon_img import Icon_img_byte
from .patch_template_img import patch_template_img_byte
from .background_img import background_img_byte
from .contact_button_img import contact_button_img_byte
from .float_window_button_img import float_window_button_img_byte
from .information_button_img import information_button_img_byte
from .choose_button_img import choose_button_img_byte
from .repair_button_img import repair_button_img_byte
from .settings_button_img import settings_button_img_byte
from .work_template_img import work_template_img_byte